CC = i686-w64-mingw32-g++
CFLAGS += -Wall -pedantic -Wextra -fPIC -O3 -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS += -static-libgcc -static-libstdc++ -lm -lpsapi  

OBJDIR := obj32

C_SOURCES := $(wildcard *.c)
C_OBJECTS := $(patsubst %.c, $(OBJDIR)/%.o, $(C_SOURCES))

all: folders evader32

folders:
	mkdir -p $(OBJDIR)

evader32: $(C_OBJECTS)
	$(CC) $(CFLAGS) -o evader32.exe $(OBJDIR)/*.o $(LDFLAGS)

$(OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f evader32.exe
	rm -rf $(OBJDIR)/*
