/*
Copyright (c) 2012, Core Security Technologies
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

// dllmain.cpp : Defines the entry point for the DLL application.
#include "stdafx.h"

#define DETECTED 1
#define NOTDETECTED 0
#define PLUGINERROR -1
#define PLATFORMNOTSUPPORTED 2

#define DllExport extern "C" __declspec(dllexport)

DllExport char* GetPluginName(void);
DllExport char* GetPluginDescription(void);
DllExport int DoMyJob(void);

HMODULE hGlobalModule;

char* GetPluginName(void)
{
	static char PluginName[] = "Detect Pin by FSTENV";
	return PluginName;
}

char* GetPluginDescription(void)
{
	static char MyDescription[] = "This plugin determines the address in which its code is actually"
								"being executed by performing a floating-point operation and then"
								"reading the FPU environment (which contains the value of the EIP"
								"register at the time the last FPU operation was performed) via the"
								"FSTENV instruction."
								"If this address does not belong to the memory range occupied by the"
								"plugin module, then it means that code generated by Pin's JIT compiler"
								"is being executed instead of the original plugin code.";
	return MyDescription;
}

int DetectEIP()
{
	DWORD MyRet;
	MEMORY_BASIC_INFORMATION mbi;

	__asm
	{

		fldz;
		fstenv [esp-0x1c];
		mov eax, [esp-0x10]
		mov MyRet, eax;
	}

	printf("MyRet is: %x\n", MyRet);

	VirtualQuery((LPCVOID)MyRet, &mbi, sizeof(mbi));

	printf("hGlobalModule is: %x -- AllocationBase is: %x\n", hGlobalModule, mbi.AllocationBase);

	if((DWORD)hGlobalModule == (DWORD)mbi.AllocationBase)
		return NOTDETECTED;
	else
		return DETECTED;
}

int DoMyJob(void)
{
	return DetectEIP();
}

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
					 )
{
	hGlobalModule = hModule;

	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
	case DLL_THREAD_ATTACH:
	case DLL_THREAD_DETACH:
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

